name: Sync Content Branch to Main

on:
  push:
    branches:
      - content

permissions:
  contents: write

jobs:
  sync-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure Git
        run: |
          # git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

<<<<<<< HEAD
      - name: Fetch branches
        run: |
          git fetch origin content
          git fetch origin main
=======
      - name: Fetch Content Branch and Sync
        run: |
          git fetch origin content
          # Extract the last commit message from the content branch
          LAST_COMMIT_MSG=$(git log origin/content -1 --pretty=%B)
          # Create a temporary directory to hold the content branch files
          mkdir temp_content
          git checkout origin/content -- . && mv * temp_content/ || true
          mv .* temp_content/ || true # Include hidden files except .git
          rm -rf temp_content/.git # Avoid moving .git directory
          mkdir -p content
          mv temp_content/* content/ || true
          mv temp_content/.* content/ || true
          rm -rf temp_content
          git add content/ # Add all files to the content directory
          git commit -m "$LAST_COMMIT_MSG" || echo "No changes to commit"
>>>>>>> 9a9ed243831688bfbcf7d180d6848183fb9255c9

      - name: Create a new branch from the source
        run: |
          git checkout content
          git checkout -b temp-working-branch

      - name: Rewrite commits with folder prefix
        run: |
          # Rewrite paths to include folder prefix
          git filter-branch --tree-filter "mkdir -p content && find . -maxdepth 1 ! -name 'content' ! -name '.' ! -name '.git' -exec mv {} content/ \;" HEAD

      - name: Checkout the target branch
        run: |
          git checkout main

      - name: Merge rewritten branch into main
        run: |
          git merge --no-ff temp-working-branch -m "Merge content branch into main with prefix 'content'"

      - name: Push changes
        run: |
          git push origin main