name: Sync Content Branch to Main

on:
  push:
    branches:
      - content

permissions:
  contents: write

jobs:
  sync-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch All Branches
        run: git fetch origin

      - name: Create Content Sync Branch
        run: |
          git checkout -b content-sync-branch origin/content

      - name: Move Content Files into /content Directory
        run: |
          mkdir -p content
          rsync -a --remove-source-files --exclude='.git/' --exclude='content/' ./ ./content/
          find . -type f -not -path './content/*' -not -path './.git/*' -delete

          # Add and commit the moved files with a single commit
          git add .
          git commit -m "Move content branch files into /content directory" || echo "No changes to commit"

      - name: Checkout Main Branch
        run: git checkout main || exit 0 # Skip checkout error if no changes are present

      - name: Merge Content into Main
        run: |
          git merge --no-ff content-sync-branch --allow-unrelated-histories
        continue-on-error: true

      - name: Resolve Conflicts (if any)
        run: |
          # Check for conflicts in the content folder
          conflicts=$(git diff --name-only --diff-filter=U | grep '^content/')

          if [ -n "$conflicts" ]; then
            echo "Conflicts found in the content folder"
            # Resolve the conflicts by favoring the 'content' branch (theirs)
            git checkout --theirs content/
            git add content/
            
            # Commit the resolution with a custom prefix for conflict resolution
            git commit -m "[Sync Resolution] Resolve conflicts in content directory"
          else
            echo "No conflicts in the content folder"
          fi

      - name: Push Changes to Main
        run: git push origin main

      - name: Cleanup Content Sync Branch
        run: |
          git branch -D content-sync-branch
