name: Sync Content Branch to Main

on:
  push:
    branches:
      - content

permissions:
  contents: write

jobs:
  sync-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure Git
        run: |
          # git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch Content Branch and Sync
        run: |
          git fetch origin content
          # Extract the last commit message from the content branch
          LAST_COMMIT_MSG=$(git log origin/content -1 --pretty=%B)
          # Create a temporary directory to hold the content branch files
          mkdir temp_content
          git checkout origin/content -- . && mv * temp_content/ || true
          mv .* temp_content/ || true # Include hidden files except .git
          rm -rf temp_content/.git # Avoid moving .git directory
          mkdir -p content
          mv temp_content/* content/ || true
          mv temp_content/.* content/ || true
          rm -rf temp_content
          git add content/ # Add all files to the content directory
          git commit -m "$LAST_COMMIT_MSG" || echo "No changes to commit"

      - name: Push Changes to Main
        run: git push origin main
