name: Sync Content Branch to Main

on:
  push:
    branches:
      - content

permissions:
  contents: write

jobs:
  sync-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch All Branches
        run: git fetch origin

      - name: Create Content Sync Branch
        run: |
          git checkout -b content-sync-branch origin/content

      - name: Sync Content to Folder
        run: |
          mkdir -p content
          rsync -a --delete --exclude='.git/' ./ ./content/
          git add .
          git commit -m "Sync content branch files to /content folder" || echo "No changes to commit"

      - name: Checkout Main Branch
        run: git checkout main

      - name: Merge Content into Main
        run: |
          git merge --no-ff content-sync-branch --allow-unrelated-histories
        continue-on-error: true

      - name: Resolve Conflicts for Content Folder
        run: |
          git status
          git diff --name-only --diff-filter=U | grep '^content/' || echo "No conflicts"
          git checkout --theirs content/
          git add content/
          git commit -m "Resolve content folder conflicts"

      - name: Push Changes to Main
        run: git push origin main

      - name: Cleanup Content Sync Branch
        run: |
          git branch -D content-sync-branch
