name: Sync Content Branch to Main

on:
  push:
    branches:
      - content

permissions:
  contents: write

jobs:
  sync-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure Git as GitHub Actor
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch branches
        run: |
          git fetch origin content
          git fetch origin main

      - name: Create Temporary Working Branch
        run: |
          git checkout -b temp-working-branch origin/content

      - name: Rewrite Paths with Folder Prefix
        run: |
          git filter-branch --tree-filter "mkdir -p content && find . -maxdepth 1 ! -name 'content' ! -name '.' ! -name '.git' -exec mv {} content/ \;" HEAD

      - name: Merge Rewritten Branch into Main
        run: |
          git checkout main
          git merge --no-ff temp-working-branch --allow-unrelated-histories

      - name: Push Changes
        run: git push origin main

      - name: Cleanup Temporary Branch
        run: |
          git branch -D temp-working-branch
